/*
 * TIMER_Config.h
 *
 *   
 *      Author: Ahmed Samy
 */

#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

/*TIMER0 MODE Options:
 * 1- TIMER0_OVERFLOW_MODE
 * 2- TIMER0_CTC_MODE
 * 3- TIMER0_FAST_PWM
 * 4- TIMER0_PHASE_CORRECT_PWM
 */
#define TIMER0_MODE TIMER0_CTC_MODE

/*TIMER0 CTC MODE OC0 PIN Options:
 * 1- TIMER0_CTC_MODE_OC0_OFF
 * 2- TIMER0_CTC_MODE_OC0_TOGGLE
 * 3- TIMER0_CTC_MODE_OC0_SET
 * 4- TIMER0_CTC_MODE_OC0_CLR*/
#define TIMER0_CTC_MODE_OC0_MODE TIMER0_CTC_MODE_OC0_SET

/*TIMER0 PRESCALER Options:
 * 1- TIMER0_OFF
 * 2- TIMER0_NO_PRESCALER
 * 3- TIMER0_8_PRESCALER
 * 4- TIMER0_64_PRESCALER
 * 5- TIMER0_256_PRESCALER
 * 6- TIMER0_1024_PRESCALER
 * 7- TIMER0_EXTERNAL_SOURCE_WITH_FALLING_EDGE
 * 8- TIMER0_EXTERNAL_SOURCE_WITH_RISING_EDGE
 */
#define TIMER0_PRESCALER TIMER0_64_PRESCALER
/*TIMER0 PWM OC0 PIN MODE Options:
 * 1- TIMER0_PWM_NON_INVERTING
 * 2- TIMER0_PWM_INVERTING
 */
#define TIMER0_PWM_OC0_PIN_MODE TIMER0_PWM_NON_INVERTING



void TIMER1_voidInit(void);

#endif /* TIMER_CONFIG_H_ */
